BASE_DIR: "F:\"
INFORMATICA_DIR: "{{ BASE_DIR }}\informatica"
SOFTWARE_DIR: "{{ BASE_DIR }}\software"
INFORMATICA_SOFT_DIR: "{{ SOFTWARE_DIR }}\informatica"
INFA_HOME: "{{ INFORMATICA_DIR }}\Apps"
POSTGRES_DIR: "{{ BASE_DIR }}\postgres"
POSTGRES_VER: "10.3"
RATING_DIR: "{{ BASE_DIR }}\rating"
RATING_SCRIPTS_DIR: "{{ RATING_DIR }}\rating_etl_shell_scripts"
RATING_WSDL_DIR: "{{ RATING_DIR }}\wsdl"