# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  name: Clone_GCInt_Repo
  inputs:
    script: 'git clone "https://Thomas.Righele:wsm7mv4mjik3zxjlyarwyvmfbgx6n3wsjxdenit5y5tqrwyjchkq@guycarp.visualstudio.com/GC%20Integration/_git/GC%20Integration"'

- task: CmdLine@2
  name: Give_Permissions
  inputs:
    script: 'chmod +x "$(System.DefaultWorkingDirectory)/GC%20Integration/IICS Asset Management Utility/iics_linux"'
- task: CmdLine@2
  name: Export_IICS_Package
  inputs:
    script: '"$(System.DefaultWorkingDirectory)/GC%20Integration/IICS Asset Management Utility/iics_linux" export --artifacts "Explore/DevOps_POC.Project" --name "TestTom" --password "nVV89ZvV3aBsw5FT" --podHostName "dm-us.informaticacloud.com" --region "us" --username "Thomas.Righele_dev@guycarp.com" --zipFilePath "$(System.DefaultWorkingDirectory)/TEST/TestTom.zip"'

- task: CmdLine@2
  name: Remove_Clone
  inputs:
    script: 'rm -R -f "GC%20Integration"'

- task: CmdLine@2
  name: Git_Add
  inputs:
    script: 'git config --global user.email "thomas.righele@guycarp.com" && git config --global user.name "Tom Righele" && git add . && git commit -m "update"'

- task: CmdLine@2
  name: Git_Pull
  inputs:
    script: 'git pull https://Thomas.Righele:wsm7mv4mjik3zxjlyarwyvmfbgx6n3wsjxdenit5y5tqrwyjchkq@guycarp.visualstudio.com/GC%20Integration/_git/IICS%20DevOps'
    

- task: CmdLine@2
  name: Git_Push
  inputs:
    script: 'git push origin master' 

