# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  name: Variable_Test
  displayName: Echoing out Variables for testing
  inputs:
    script: |
      echo "User is: $(Build.QueuedBy)"
      echo "Useremail is: "
      echo "Repo Name is: $(Build.Repository.Name)"
