# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  name: test1
  inputs:
    script: 'echo $(System.DefaultWorkingDirectory)/'

- task: CmdLine@2
  inputs:
    script: 'dir $(System.DefaultWorkingDirectory)'


