# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  name: Give_Permissions
  inputs:
    script: 'chmod +x "$(System.DefaultWorkingDirectory)/TEST/iics_linux"'
- task: CmdLine@2
  inputs:
    script: '$(System.DefaultWorkingDirectory)/TEST/iics_linux --help'