# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  name: Clone_GCInt_Repo
  inputs:
    script: 'git clone "https://Thomas.Righele:wsm7mv4mjik3zxjlyarwyvmfbgx6n3wsjxdenit5y5tqrwyjchkq@guycarp.visualstudio.com/GC%20Integration/_git/GC%20Integration"'


- task: BatchScript@1
  inputs:
    filename: 'iics.exe'
    arguments: '--help'
    workingFolder: '"$(System.DefaultWorkingDirectory)/TEST"'