# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: BatchScript@1
  inputs:
    filename: '$(System.DefaultWorkingDirectory)/_GC Integration/IICS Asset Management Utility/iics.exe'
    arguments: 'iics export --artifacts "Explore/DevOps_POC.Project" --name "TestTom" --password "nVV89ZvV3aBsw5FT" --podHostName "dm-us.informaticacloud.com" --region "us" --username "Thomas.Righele_dev@guycarp.com" --zipFilePath "$(Build.ArtifactStagingDirectory)/_IICS DevOps/Test/TestTom.zip"'

- task: CmdLine@2
  inputs:
    script: |
      echo git --version
      
      echo Hello world
