---

- name: create rating base dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '755'
  with_items:
    - "{{ RATING_SCRIPTS_DIR }}"
    - "{{ RATING_WSDL_DIR }}"

- name: copy rating shell scripts
  copy:
    src: "{{ item }}"
    dest: "{{ RATING_SCRIPTS_DIR }}/"
    mode: '755'
  delegate_to: localhost
  with_items:
    - ambest_failed_notification.sh
    - ambest_validation_notification.sh
    - ent_rating_ambest_account_rating.sh
    - ent_rating_ambest_param.sh
    - non_trading_partner_failed_notification.sh
    - non_trading_partner_validation_notification.sh
    - snp_failed_notification.sh
    - snp_validation_notification.sh

- name: copy wsdl file
  copy:
    src: "{{ item }}"
    dest: "{{ RATING_WSDL_DIR }}/"
    mode: '755'
  delegate_to: localhost
  with_items:
    - AMBest_CustomServiceSoap12.wsdl