---

- name: add environment variariables in .profile
  lineinfile: 
    dest: "/home/{{ app_user }}/.bash_profile"
    insertafter: "EOF"
    line: "{{ item.line }}"
  delegate_to: localhost
  with_items:
    - { line: 'export AMBEST_RATING_PASSWORD="{{ RATING_PWD }}"' }
    - { line: 'export AMBEST_RATING_USERID={{ RATING_USERID }}' }
    - { line: 'export RATING_PATH={{ BASE_DIR }}/rating' }
    - { line: ' ' }
    - { line: 'export PG_INSTALLATION_PATH=/bin' }
    - { line: 'export PG_GCMP_SERVER_NAME={{ GCMP_SERVER_NAME }}' }
    - { line: 'export PG_GCMP_DB={{ GCMP_DB }}' }
    - { line: 'export PG_GCMP_DB_USER_ID={{ GCMP_DB_USERID }}' }
    - { line: 'export PG_GCMP_PORT={{ GCMP_PORT }}' }
    - { line: 'export PG_GCMP_DB_PASSWORD={{ GCMP_DB_PWD }}' }
    - { line: ' ' }
    - { line: 'export JDK_HOME={{ INFA_HOME }}/jre' }
    - { line: 'export PATH="$PATH:$JDK_HOME"' }
